<?php

namespace AppBundle\Repository;

/**
 * ExcepcionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExcepcionesRepository extends \Doctrine\ORM\EntityRepository
{
}
