# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.postsService:
        class: AppBundle\Service\PostServices
        arguments: ['@doctrine.orm.entity_manager']

    app.login_listener:
        class: AppBundle\Listener\PostListener
        tags:
        - { name: doctrine.event_listener, event: postPersist, entity_manager: Post }